---
apiVersion:  helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  releaseName: nginx-ingress
  chart:
    version: 1.41.2
    repository: https://kubernetes-charts.storage.googleapis.com
    name: nginx-ingress
  values:
    controller:
      metrics:
        port: 10254
        enabled: true
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "10254"
      autoscaling:
        enabled: true
        minreplicas: 3
        maxreplicas: 6
    defaultBackend:
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 3
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: failure-domain.beta.kubernetes.io/zone
              operator: In
              values:
              - eastus2-1
              - eastus2-2
              - eastus2-3
            - key: agentpool
              operator: In
              values:
              - default
